name = "DiffusionGarnet"
uuid = "d440471f-548d-4017-b306-a3be590dd0f0"
authors = ["Hugo Dominguez"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
